http:
  listener:
    host: "localhost"
    port: "8083"
    path: "/fastGoCall/{serviceType}"
    
db:
  mysql:
    host: "127.0.0.1"
    port: "3306"
    database: "TripEasy"
    user: "root"
    password: "Badab00m"
    