#%RAML 1.0 Library
usage:
traits:
  transactionID: !include /libraries/common/traits/headers-transactionID-traits.raml
  companyName: !include /libraries/common/traits/queryParameters-companyName-traits.raml
  departureLocation: !include /libraries/common/traits/queryParameters-departureLocation-traits.raml
  destinationLocation: !include /libraries/common/traits/queryParameters-destinationLocation-traits.raml
  requestTimezone: !include /libraries/common/traits/queryParameters-requestTimezone-traits.raml


