http:
  listener:
    host: "localhost"
    port: "8085"
  requester:
    travelTip:
      host: "localhost"
      port: "8083"
      routesPath: "/travelTipCall/routes"
      schedulesPath: "/travelTipCall/schedules"
    fastGo:
      host: "localhost"
      port: "8084"
      routesPath: "/travelTipCall/routes"
      schedulesPath: "/travelTipCall/schedules"